version: '3.4'

services:
  honeypot:
    image: honeypot
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash -c "/usr/bin/docker-entrypoint.sh"
    volumes:
      - .:/honeypot
    ports:
      - 3019:3019
