FROM nginx:1.19.2

RUN mkdir /project_root

COPY --chown=101 docker/wait-for-it.sh /project_root/wait-for-it.sh
COPY --chown=101 docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --chown=101 docker/nginx_entry.sh /project_root/nginx_entry.sh

RUN chmod u+x /project_root/wait-for-it.sh && chmod u+x /project_root/nginx_entry.sh