FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update 
RUN apt-get install -y iipimage-server
RUN apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

USER www-data
ENTRYPOINT ["/usr/lib/iipimage-server/iipsrv.fcgi", "--bind", "0.0.0.0:9000", "--backlog", "1024"]