# Store non-sensitive configuration settings here.  Acessible from Rails.configuration.settings
defaults: &defaults
  image_path: 'public/images'
  vips_command: 'vips'
  vips_thumbnail_command: 'vipsthumbnail'

local: &local
  <<: *defaults
  host: localhost
  port: 3019
  protocol: 'http'

vm: &vm
  <<: *defaults
  vips_command: '/usr/local/bin/vips'
  vips_thumbnail_command: '/usr/local/bin/vipsthumbnail'
  protocol: 'https'

development:
  <<: *local

test:
  <<: *local

pre_production:
  <<: *vm
  host: honeypotpprd.library.nd.edu

production:
  <<: *vm
  host: honeypot.library.nd.edu
